### ISSUE TITLE
More elegant failure with faulty place files

### ISSUE THREAD

**Issue by matsen** [matsen/pplacer#310]
When parsing a problematic place file, such as one produced in the presence of zero length branch lengths leading to `-nan` and `-inf` values, guppy does not fail especially beautifully, saying things like

```
"Uncaught exception: syntax error lexing between line 472 character 18 and line 472 character 19 of StationP1HLIP.hma.jplace
Fatal error: exception Ppatteries.Sparse.Parse_error("syntax error lexing", _, _, _)"
```

It would be nice to fail more nicely.

**Comment by AlessioMilanese** [comment]
I got a similar error:
```
Uncaught exception: syntax error parsing between line 1 character 25 and line 1 character 26 of /congo/data/milanese/test_pplacer/fssfdmy.refpkg/refseqs.fasta_oldrefalign.tre
Fatal error: exception Ppatteries.Sparse.Parse_error("syntax error parsing", _, _, _)
Traceback (most recent call last):
  File "/congo/data/milanese/miniconda_3.7/bin/miniconda/bin/taxit", line 8, in <module>
    sys.exit(main())
  File "/congo/data/milanese/miniconda_3.7/bin/miniconda/lib/python3.7/site-packages/taxtastic/scripts/taxit.py", line 51, in main
    return action(arguments)
  File "/congo/data/milanese/miniconda_3.7/bin/miniconda/lib/python3.7/site-packages/taxtastic/subcommands/create.py", line 165, in action
    r.reroot(rppr=args.rppr)
  File "<decorator-gen-4>", line 2, in reroot
  File "/congo/data/milanese/miniconda_3.7/bin/miniconda/lib/python3.7/site-packages/taxtastic/refpkg.py", line 132, in transaction
    return f(self, *args, **kwargs)
  File "/congo/data/milanese/miniconda_3.7/bin/miniconda/lib/python3.7/site-packages/taxtastic/refpkg.py", line 498, in reroot
    '-c', self.path, '-o', name])
  File "/congo/data/milanese/miniconda_3.7/bin/miniconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['rppr', 'reroot', '-c', '/congo/data/milanese/test_pplacer/fssfdmy.refpkg', '-o', '/tmp/treeg8ez94_a.tre']' returned non-zero exit status 2.
```

At the beginning I thought it was because of duplicates (reading this issue). But then I read more carefully the message:
```
error parsing between line 1 character 25 and line 1 character 26 of refseqs.fasta_oldrefalign.tre
```

and looking at the tree:
```
(d__Bacteriap__Firmicutes;c__Bacilli;o__Staphyl ...
```
The issue is with the `;`.
