### ISSUE TITLE
Erro while running  pplacer with gtdbtk

### ISSUE THREAD

**Issue by hites77** [matsen/pplacer#370]
Follwing error code generated when using pplacer, it run perfectly on test.
[2019-09-08 23:33:08] INFO: Placing 21 bacterial genomes into reference tree with pplacer (be patient).
[2019-09-09 00:31:17] ERROR: An error was encountered while running pplacer.
[2019-09-09 00:31:19] ERROR: Controlled exit resulting from an unrecoverable error or warning.

================================================================================
EXCEPTION: PplacerException
  MESSAGE: 
________________________________________________________________________________

Traceback (most recent call last):
  File "/home/bioinfo/.local/bin/gtdbtk", line 452, in <module>
    gt_parser.parse_options(args)
  File "/home/bioinfo/.local/lib/python2.7/site-packages/gtdbtk/main.py", line 602, in parse_options
    self.classify(options)
  File "/home/bioinfo/.local/lib/python2.7/site-packages/gtdbtk/main.py", line 415, in classify
    options.debug)
  File "/home/bioinfo/.local/lib/python2.7/site-packages/gtdbtk/classify.py", line 320, in run
    scratch_dir)
  File "/home/bioinfo/.local/lib/python2.7/site-packages/gtdbtk/classify.py", line 146, in place_genomes
    pplacer.run(self.cpus, 'WAG', pplacer_ref_pkg, pplacer_json_out, user_msa_file, pplacer_out, pplacer_mmap_file)
  File "/home/bioinfo/.local/lib/python2.7/site-packages/gtdbtk/external/pplacer.py", line 61, in run
    raise PplacerException(proc_err)
PplacerException
================================================================================

command used was
gtdbtk classify_wf --genome_dir /home/bioinfo/Downloads/binI/ --out_dir /home/bioinfo/binclassI --cpus 26 --ext fa

system has 50Gb of RAM

**Comment by matsen** [comment]
None of this has any pplacer output. Ask the gtdbtk authors.
