### ISSUE TITLE
rppr reroot failure

### ISSUE THREAD

**Issue by lpipes** [matsen/pplacer#381]
This seems to be failing on `rppr` reroot. I'm not sure what the issue is because I've used this exact same command on other files for some compositions of Bacteria I can't get this command to work.
```
taxit create --clobber --rppr /space/s1/lenore/software/pplacer/bin/bin/rppr -P 0.refpkg -l COI --taxonomy 0_taxonomyfromtaxids2.csv --aln-fasta 0_MSA.fasta --tree-stats RAxML_info.0 --tree-file RAxML_bestTree.0.reroot --seq-info updated4.csv 
rppr: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Traceback (most recent call last):
  File "/space/s1/lenore/software/taxtastic_2/taxtastic/taxit.py", line 22, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/space/s1/lenore/software/taxtastic_2/taxtastic/taxtastic/scripts/taxit.py", line 51, in main
    return action(arguments)
  File "/space/s1/lenore/software/taxtastic_2/taxtastic/taxtastic/subcommands/create.py", line 168, in action
    r.reroot(rppr=args.rppr)
  File "/home/lenore/.local/lib/python3.10/site-packages/decorator-5.1.1-py3.10.egg/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/space/s1/lenore/software/taxtastic_2/taxtastic/taxtastic/refpkg.py", line 132, in transaction
    return f(self, *args, **kwargs)
  File "/space/s1/lenore/software/taxtastic_2/taxtastic/taxtastic/refpkg.py", line 497, in reroot
    subprocess.check_call([rppr or 'rppr', 'reroot',
  File "/home/lenore/Python-3.10.3/Lib/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/space/s1/lenore/software/pplacer/bin/bin/rppr', 'reroot', '-c', '/space/s1/lenore/trout_copy/s2_copy/from_tilden/bacteria_radom_set/0/0.refpkg', '-o', '/tmp/tree82gsjmw0.tre']' died with <Signals.SIGABRT: 6>.
```
[updated4.csv](https://github.com/matsen/pplacer/files/13959497/updated4.csv)
[0_taxonomyfromtaxids2.csv](https://github.com/matsen/pplacer/files/13959498/0_taxonomyfromtaxids2.csv)
[RAxML_bestTree.0.reroot.txt](https://github.com/matsen/pplacer/files/13959507/RAxML_bestTree.0.reroot.txt)
[RAxML_info.0.txt](https://github.com/matsen/pplacer/files/13959508/RAxML_info.0.txt)
[0_MSA.fasta.txt](https://github.com/matsen/pplacer/files/13959510/0_MSA.fasta.txt)

**Comment by matsen** [comment]
Lenore-- I'm sorry to say that this is a problem between the compiler and your machine and doesn't have to do with our code.

To double check, you're saying that this is only triggered for some input files, running on exactly the same machine?

**Comment by lpipes** [comment]
Hi Erick, I removed all entries that had a `clade` taxonomic rank associated with it and the command seems to have worked (I also had to prune the tree)
```
taxit create --clobber --rppr /space/s1/lenore/software/pplacer/bin/bin/rppr -P 0.refpkg -l COI --taxonomy 0_taxonomyfromtaxids_edit.csv --aln-fasta 0_MSA.fasta --tree-stats RAxML_info.0 --tree-file prunedtree.nw --seq-info 0_edit.csv 
rerooting at phylum
root found at node 3519
```
It seems that this is because `clade` is an unordered rank but over half of my entries have a `clade` taxonomic rank. See https://github.com/fhcrc/taxtastic/issues/155

**Comment by lpipes** [comment]
The fix in `taxtastic` seems to have fixed this issue. Thanks for your help!
